# Generated by Django 4.1.7 on 2023-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
