# Generated by Django 4.1.7 on 2023-05-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_alter_usermaster_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter the main content of the for your bio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experince',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pin',
            field=models.IntegerField(auto_created=True, blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill',
            field=models.CharField(blank=True, error_messages={'unique': 'A candidate with this skill already exists.'}, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='education',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pin',
            field=models.IntegerField(auto_created=True, blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.DateField(auto_now_add=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='jobs_app/img/candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
