# Generated by Django 4.2.1 on 2023-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0005_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
