# Generated by Django 4.2.1 on 2023-06-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0006_usermaster_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='username',
        ),
    ]
