# Generated by Django 4.2.1 on 2023-07-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0008_skill_remove_company_address_remove_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='role',
        ),
    ]
