# Generated by Django 4.2.1 on 2023-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0012_alter_usermaster_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
